"""Reports: JSON for machines, Markdown for the coding agent, HTML for humans."""

from __future__ import annotations

import html
import json
import time
from pathlib import Path
from typing import Any


def _step_text(step: dict[str, Any]) -> str:
    a = step.get("action", {})
    if "steps" in a:
        return ", then ".join(_step_text({"action": x}) for x in a["steps"])
    if "close_panel" in a:
        return f"close `{a['close_panel']}` with its close button"
    if "key" in a:
        return f"press `{a['key']}`"
    if "click_text" in a:
        return f'click the control labelled "{a["click_text"]}"'
    if "click_sel" in a:
        return f"click `{a['click_sel']}`"
    if "click_xy" in a:
        return f"click at ({a['click_xy'][0]}, {a['click_xy'][1]})"
    return json.dumps(a)


def write_json(path: Path, run: dict[str, Any]) -> None:
    path.write_text(json.dumps(run, indent=2, default=str), encoding="utf-8")


def write_markdown(path: Path, run: dict[str, Any]) -> None:
    f = run["findings"]
    meta = run["meta"]
    lines = [
        f"# Playtest report: {meta.get('target')}",
        "",
        f"Commit `{meta.get('commit') or 'n/a'}` · viewport {meta.get('viewport')} · {meta.get('time')} · Solari session `{(meta.get('browser_session') or '')[-12:]}`",
        f"WebGL: {meta.get('webgl', {}).get('renderer', 'n/a')} · canvas colours {meta.get('canvas', {}).get('distinct_colours', 'n/a')} · {meta.get('fps', 0):.0f} fps",
        f"Controls discovered: {', '.join(c['label'] for c in run.get('controls', [])) or 'none'} · sequences run: {run.get('sequences', 0)}",
        "Replay: "
        + (
            "presigned rrweb link in report.json (valid about 15 minutes)"
            if meta.get("replay_url")
            else "not available"
        ),
        "",
        f"## {len(f)} finding(s)" if f else "## No findings",
        "",
    ]
    if not f:
        lines.append(
            "Every discovered panel stayed usable across all open/close sequences, no console errors, canvas renders."
        )
    for x in f:
        lines += [
            f"### {x['id']} · {x['severity'].upper()} · {x['title']}",
            "",
            "**Reproduce** (from a fresh load, after the start screen):",
            "",
        ]
        for i, s in enumerate(x["sequence"], 1):
            lines.append(f"{i}. {_step_text(s)}  ·  _{s.get('intent', '')}_")
        if not x["sequence"]:
            lines.append("1. Load the game and wait for the first frame.")
        ev = x.get("evidence", {})
        lines += ["", "**Evidence**", ""]
        if "panel" in ev:
            p = ev["panel"]
            lines.append(
                f"- `{p['sel']}` rect: x={p['x']} y={p['y']} w={p['w']} h={p['h']} (open={p['open']}, inside viewport={p['inside']})"
            )
        if ev.get("reference"):
            r = ev["reference"]
            lines.append(f"- same panel opened alone from a clean state: w={r['w']} h={r['h']}")
        if ev.get("measure"):
            m = ev["measure"]
            lines.append(
                f"- computed: display={m.get('display')} flex={m.get('flex')} min-height={m.get('minHeight')} overflow={m.get('overflow')} parent=`{m.get('parent')}`"
            )
            if m.get("siblings"):
                lines.append(f"- siblings in the same container: {', '.join(m['siblings'])}")
        if ev.get("open_panels"):
            lines.append(
                "- open panels at that moment: "
                + "; ".join(f"`{q['sel']}` {q['w']}×{q['h']}" for q in ev["open_panels"])
            )
        if ev.get("console"):
            lines.append("- console: " + " | ".join(str(c)[:160] for c in ev["console"][:5]))
        if ev.get("fps"):
            lines.append(f"- fps {ev['fps']:.0f} on {ev.get('renderer')}")
        for s in x.get("screenshots", []):
            lines.append(f"- screenshot: `{s}`")
        lines += [
            "",
            f"**Hypothesis** {x['hypothesis']}",
            "",
            f"**Falsifier** {x['falsifier']}",
            "",
            "**Verify the fix** re-run the same sequence and check the falsifier holds.",
            "",
        ]
    lines += [
        "",
        "---",
        "",
        "Generated by solari-playtest. The sequences above are deterministic: replay them with `playtest replay <report.json>`.",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;700&display=swap');
:root{--bg:#080a0e;--panel:#0f1514;--line:#263634;--fg:#e7e7e2;--muted:#939599;--dim:#474747;--accent:#f5b301;--green:#9bd89a;--red:#ff5c5c;--yellow:#f5c66a}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 Inter,system-ui,sans-serif}
main{max-width:1080px;margin:0 auto;padding:48px 28px 80px}
header{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid var(--accent);padding-bottom:14px;font-family:"JetBrains Mono",monospace}
.brand{font-size:16px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.brand b{color:var(--accent)}.meta{color:var(--muted);font-size:11px;letter-spacing:.1em;text-transform:uppercase}
h1{font-size:44px;font-weight:600;line-height:1.02;letter-spacing:-.02em;margin:28px 0 6px}h1 span{color:var(--accent)}
.sub{color:var(--muted);margin:0 0 28px;font-family:"JetBrains Mono",monospace;font-size:12px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:2px;margin:0 0 32px}.tile{background:var(--bg);padding:16px 18px;box-shadow:0 0 0 1px var(--line);font-family:"JetBrains Mono",monospace}
.tile .k{color:var(--muted);font-size:10px;letter-spacing:.16em;text-transform:uppercase}.tile .v{font-size:26px;font-weight:700;margin-top:6px}.v.bad{color:var(--red)}
section{border-top:1px solid var(--line);padding:22px 0 8px}section h2{margin:0 0 6px;font-size:20px;font-weight:600;display:flex;gap:10px;align-items:center}
.sev{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.1em;padding:3px 9px;color:#080a0e;font-weight:700}.high{background:var(--red)}.medium{background:var(--yellow)}.low{background:var(--muted)}
ol{margin:6px 0 14px 20px}code{font-family:"JetBrains Mono",monospace;font-size:13px;color:var(--accent)}
.ev{color:var(--muted);font-size:13px;font-family:"JetBrains Mono",monospace}.ev li{margin:2px 0}
img{max-width:100%;border:1px solid var(--line);margin:10px 0}
.hyp{margin:10px 0 0}.hyp b{color:var(--accent)}
footer{color:var(--dim);font-size:11px;margin-top:32px;border-top:1px solid var(--line);padding-top:14px;font-family:"JetBrains Mono",monospace;text-transform:uppercase;letter-spacing:.06em}
"""


def write_html(path: Path, run: dict[str, Any]) -> None:
    e = lambda x: html.escape("" if x is None else str(x))
    meta = run["meta"]
    f = run["findings"]
    tiles = [
        ("findings", str(len(f))),
        ("high", str(sum(1 for x in f if x["severity"] == "high"))),
        ("controls", str(len(run.get("controls", [])))),
        ("sequences", str(run.get("sequences", 0))),
        ("fps", f"{meta.get('fps', 0):.0f}"),
        ("canvas colours", str(meta.get("canvas", {}).get("distinct_colours", "n/a"))),
    ]
    tiles_html = "".join(
        f"<div class=tile><div class=k>{e(k)}</div><div class='v{' bad' if k == 'high' and v != '0' else ''}'>{e(v)}</div></div>"
        for k, v in tiles
    )
    secs = []
    for x in f:
        steps = (
            "".join(
                f"<li>{e(_step_text(s))} <span class=ev>{e(s.get('intent', ''))}</span></li>"
                for s in x["sequence"]
            )
            or "<li>Load the game and wait for the first frame.</li>"
        )
        ev = x.get("evidence", {})
        evl = []
        if "panel" in ev:
            p = ev["panel"]
            evl.append(
                f"<li><code>{e(p['sel'])}</code> rect x={p['x']} y={p['y']} w={p['w']} h={p['h']}</li>"
            )
        if ev.get("reference"):
            evl.append(f"<li>opened alone: w={ev['reference']['w']} h={ev['reference']['h']}</li>")
        if ev.get("measure") and ev["measure"].get("siblings"):
            evl.append(f"<li>siblings: {e(', '.join(ev['measure']['siblings']))}</li>")
        if ev.get("console"):
            evl.append(f"<li>console: {e(' | '.join(str(c)[:140] for c in ev['console'][:4]))}</li>")
        shots = "".join(f"<img src='{e(Path(s).name)}' alt='evidence'>" for s in x.get("screenshots", [])[:2])
        secs.append(
            f"<section><h2><span class='sev {e(x['severity'])}'>{e(x['severity'].upper())}</span>{e(x['title'])}</h2><b>Reproduce</b><ol>{steps}</ol><ul class=ev>{''.join(evl)}</ul>{shots}<p class=hyp><b>Hypothesis</b> {e(x['hypothesis'])}</p><p class=hyp><b>Falsifier</b> {e(x['falsifier'])}</p></section>"
        )
    doc = f"""<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>playtest · {e(meta.get("target"))}</title><style>{CSS}</style></head>
<body><main><header><div class=brand><b>▮ PLAYTEST</b> <b>///</b> REPORT</div><div class=meta>{e(meta.get("time"))} · {e((meta.get("commit") or "n/a")[:10])} · {e(meta.get("viewport"))}</div></header>
<h1>{e(meta.get("target"))} <span>playtest</span></h1><p class=sub>Built in a Solari sandbox, played in a Solari Chrome ({e(meta.get("webgl", {}).get("renderer", "n/a"))}). Replay: {"rrweb link in report.json, presigned for about 15 minutes" if meta.get("replay_url") else "n/a"}</p>
<div class=grid>{tiles_html}</div>{"".join(secs) or "<section><h2>No findings</h2><p class=ev>Every discovered panel stayed usable across all sequences.</p></section>"}
<footer>generated by solari-playtest · {e(time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))}</footer></main></body></html>"""
    path.write_text(doc, encoding="utf-8")
